# Generated by Django 4.0.4 on 2022-06-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.URLField(blank=True, default='https://images.nightcafe.studio//assets/profile.png?tr=w-1600,c-at_max', null=True),
        ),
    ]
