# Generated by Django 4.0.4 on 2022-06-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_comment_author_alter_comment_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, default='https://media.istockphoto.com/photos/various-sports-equipment-balls-on-wooden-background-picture-id1145660545?b=1&k=20&m=1145660545&s=170667a&w=0&h=-oZeH_yvbCkH4S4t8XrPpqb3UykS8dntaa693L_6r4A=', null=True),
        ),
    ]
